import os

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "sraGbRmjYQXmYdnrgPk!OFE35UP6n/QqeoED=iu/bUXBFSSPwnsuprP6T45Qsbwywu2khUka!6IIleY",
)
if not SECRET_KEY:
    SECRET_KEY = os.urandom(32)

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRES_MINUTES = 30
REFRESH_TOKEN_EXPIRES_MINUTES = 15 * 24 * 60  # 15 days


POSTGRES_HOST = os.getenv("POSTGRES_HOST", "0.0.0.0")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")
POSTGRES_USER = os.getenv("POSTGRES_USER", "user")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "user")
POSTGRES_DB = os.getenv("POSTGRES_DB", "user")

ORACLE_HOST = os.getenv("ORACLE_HOST", "192.168.0.253")
ORACLE_HOST_PORT = os.getenv("ORACLE_PORT", "1521")
ORACLE_USER = os.getenv("ORACLE_USER", "mgp")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD", "MGP")
ORACLE_DB = os.getenv("ORACLE_DB", "TPSN")