from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class AlinanSiparis(Base):
    __tablename__ = 'alinan_siparis'

    yil: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    ay: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    siparis_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    tarife_no: Mapped[Optional[Float]] = mapped_column(Float)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    kimlik_no: Mapped[Optional[Float]] = mapped_column(Float)
    banka_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    hesap_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    ref_belge: Mapped[Optional[String]] = mapped_column(String)
    sevk_yeri: Mapped[Optional[String]] = mapped_column(String)
    teslim_sekli: Mapped[Optional[String]] = mapped_column(String)
    gorusulen_kisi: Mapped[Optional[String]] = mapped_column(String)
    tasima_bedeli: Mapped[Optional[Float]] = mapped_column(Float)
    odeme_sekli: Mapped[Optional[String]] = mapped_column(String)
    durumu: Mapped[Optional[String]] = mapped_column(String)
    kayit_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    istenilen_termin: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    onerilen_termin: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kesinlesen_termin: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    fatura_irsaliye_fl: Mapped[Optional[String]] = mapped_column(String)
    araci_firma: Mapped[Optional[Integer]] = mapped_column(Integer)
    musteri_termini: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    onaylayan: Mapped[Optional[Float]] = mapped_column(Float)
    onay_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    hareket_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    ambar_kimlik_no: Mapped[Optional[Float]] = mapped_column(Float)
    ambar_sevk_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    ref_belge_no: Mapped[Optional[String]] = mapped_column(String)
    alt_durumu: Mapped[Optional[String]] = mapped_column(String)
    kesinlesme_ciddiyeti: Mapped[Optional[Float]] = mapped_column(Float)
    fatura_kesilme_fl: Mapped[Optional[String]] = mapped_column(String)
    birim_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    teslim_suresi: Mapped[Optional[String]] = mapped_column(String)
    iskonto_tutari: Mapped[Optional[Float]] = mapped_column(Float)
    iskonto_yuzdesi: Mapped[Optional[Float]] = mapped_column(Float)
    opsiyon: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    garanti_suresi: Mapped[Optional[String]] = mapped_column(String)
    bagimli_yil: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_ay: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_siparis_no: Mapped[Optional[Float]] = mapped_column(Float)
    icerik: Mapped[Optional[String]] = mapped_column(String)
    iade_no: Mapped[Optional[String]] = mapped_column(String)
    gizli: Mapped[Optional[Integer]] = mapped_column(Integer)
    irsaliye_no: Mapped[Optional[String]] = mapped_column(String)
    siparis_bayi_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    baski_sayisi: Mapped[Optional[String]] = mapped_column(String)
    sip_iade_no: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    fiyat_tarifesi: Mapped[Optional['FiyatTarifesi']] = relationship(back_populates='alinan_siparis')
    firma: Mapped[Optional['Firma']] = relationship(back_populates='alinan_siparis')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='alinan_siparis')
    banka_hesabi: Mapped[Optional['BankaHesabi']] = relationship(back_populates='alinan_siparis')
    firma_1: Mapped[Optional['Firma']] = relationship(back_populates='alinan_siparis')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='alinan_siparis')
    organizasyon_birimi: Mapped[Optional['OrganizasyonBirimi']] = relationship(back_populates='alinan_siparis')
    hareket_sebebi: Mapped[Optional['HareketSebebi']] = relationship(back_populates='alinan_siparis')
    kisi_1_2: Mapped[Optional['Kisi']] = relationship(back_populates='alinan_siparis')
