from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class AlinanSiparisDetay(Base):
    __tablename__ = 'alinan_siparis_detay'

    yil: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    ay: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    siparis_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    sira_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    teslim_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    iade_yil: Mapped[Optional[Float]] = mapped_column(Float)
    iade_ay: Mapped[Optional[Float]] = mapped_column(Float)
    iade_fis_no: Mapped[Optional[Float]] = mapped_column(Float)
    kaydeden: Mapped[Optional[Float]] = mapped_column(Float)
    iptal_eden: Mapped[Optional[Float]] = mapped_column(Float)
    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    termin_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_z: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_nedeni: Mapped[Optional[String]] = mapped_column(String)
    kayit_z: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    sevk_z: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kesinlesme_z: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    lot_no: Mapped[Optional[String]] = mapped_column(String)
    tanimi: Mapped[Optional[String]] = mapped_column(String)
    ambalaj: Mapped[Optional[String]] = mapped_column(String)
    miktar: Mapped[Optional[Float]] = mapped_column(Float)
    tutar: Mapped[Optional[Float]] = mapped_column(Float)
    para_birimi: Mapped[Optional[String]] = mapped_column(String)
    uygulanan_iskonto: Mapped[Optional[Float]] = mapped_column(Float)
    gerekce: Mapped[Optional[Float]] = mapped_column(Float)
    istenilen_termin_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    onerilen_termin_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    ce_fl: Mapped[Optional[String]] = mapped_column(String)
    temin_fl: Mapped[Optional[String]] = mapped_column(String)
    miktar_iade: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_uretim: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_donusum: Mapped[Optional[Integer]] = mapped_column(Integer)
    miktar_karsilanacak: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    miktar_tedarikci: Mapped[Optional[Integer]] = mapped_column(Integer)
    miktar_eldeki: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_fason: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_satinalma: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_mp_uretim: Mapped[Optional[Float]] = mapped_column(Float)
    etiket_fl: Mapped[Optional[String]] = mapped_column(String)
    ce_numarasi: Mapped[Optional[String]] = mapped_column(String)
    markalama: Mapped[Optional[String]] = mapped_column(String)
    miktar_iade_siparis: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_musteri: Mapped[Optional[Float]] = mapped_column(Float)
    teknik_ozellik: Mapped[Optional[String]] = mapped_column(String)
    adi: Mapped[Optional[String]] = mapped_column(String)
    bagimli_yil: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_ay: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_siparis_no: Mapped[Optional[Float]] = mapped_column(Float)
    urun_grup_no: Mapped[Optional[Float]] = mapped_column(Float)
    tarife_no: Mapped[Optional[Float]] = mapped_column(Float)
    log_record_id: Mapped[Optional[String]] = mapped_column(String)
    etiket_firma: Mapped[Optional[String]] = mapped_column(String)
    son_kullanma_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    ce_bilgisi: Mapped[Optional[String]] = mapped_column(String)
    hareket_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    irsaliye_no: Mapped[Optional[String]] = mapped_column(String)
    iade_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    yeni_program: Mapped[Optional[Integer]] = mapped_column(Integer)
    sut_fiyat_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    bilgiislem_note: Mapped[Optional[String]] = mapped_column(String)
    istenen_stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    udi_barcode: Mapped[Optional[String]] = mapped_column(String)
    alinan_siparis: Mapped[Optional['AlinanSiparis']] = relationship(back_populates='alinan_siparis_detay')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='alinan_siparis_detay')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='alinan_siparis_detay')
    para_birimi: Mapped[Optional['ParaBirimi']] = relationship(back_populates='alinan_siparis_detay')
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='alinan_siparis_detay')
    alinan_iade: Mapped[Optional['AlinanIade']] = relationship(back_populates='alinan_siparis_detay')
    alinan_siparis_teslimi: Mapped[Optional['AlinanSiparisTeslimi']] = relationship(
        back_populates='alinan_siparis_detay')
    alinan_siparis_detay: Mapped[Optional['AlinanSiparisDetay']] = relationship(back_populates='alinan_siparis_detay')
