from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class IsEmri(Base):
    __tablename__ = 'is_emri'

    tanzim_eden: Mapped[Optional[Float]] = mapped_column(Float)
    teslim_alan: Mapped[Optional[Float]] = mapped_column(Float)
    lot_no: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    teslim_saati: Mapped[Optional[String]] = mapped_column(String)
    talep_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    ek_bilgi: Mapped[Optional[String]] = mapped_column(String)
    teslim_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    is_emri_gerekcesi: Mapped[Optional[String]] = mapped_column(String)
    ref_belge_no: Mapped[Optional[String]] = mapped_column(String)
    oncelik: Mapped[Optional[String]] = mapped_column(String)
    kk_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    miktar_talep: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_uretim: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_red: Mapped[Optional[Float]] = mapped_column(Float)
    baski_sayisi: Mapped[Optional[Float]] = mapped_column(Float)
    recete_no: Mapped[Optional[Float]] = mapped_column(Float)
    arsiv_fl: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    ue_fis_no: Mapped[Optional[Float]] = mapped_column(Float)
    ue_yil: Mapped[Optional[Float]] = mapped_column(Float)
    isemri_no: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    dogus_lotno: Mapped[Optional[String]] = mapped_column(String)
    miktar_kabul: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_sartli_kabul: Mapped[Optional[Float]] = mapped_column(Float)
    ue_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    depo_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    urun_lotsuz: Mapped[Optional[String]] = mapped_column(String)
    hareket_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    kapanis_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    durumu: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    ce_fl: Mapped[Optional[Float]] = mapped_column(Float)
    termin_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_kimlik: Mapped[Optional[Float]] = mapped_column(Float)
    iptal_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_gerekcesi: Mapped[Optional[String]] = mapped_column(String)
    grup_is_emri: Mapped[Optional[String]] = mapped_column(String)
    siparis_no: Mapped[Optional[String]] = mapped_column(String)
    uyg_yil: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_ay: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_yil: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_ay: Mapped[Optional[Float]] = mapped_column(Float)
    sip_siparis_no: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    kayit_no: Mapped[Optional[Float]] = mapped_column(Float)
    refakat_kart_no: Mapped[Optional[String]] = mapped_column(String)
    miktar_reserve: Mapped[Optional[Float]] = mapped_column(Float)
    kayit_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iade_yil: Mapped[Optional[Float]] = mapped_column(Float)
    iade_ay: Mapped[Optional[Float]] = mapped_column(Float)
    iade_fis_no: Mapped[Optional[Float]] = mapped_column(Float)
    steril_fl: Mapped[Optional[String]] = mapped_column(String)
    islem_merkezi_id: Mapped[Optional[String]] = mapped_column(String)
    isemri_yil: Mapped[Optional[Integer]] = mapped_column(Integer)
    tek_barkod: Mapped[Optional[String]] = mapped_column(String)
    ce_resim_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    int_lot: Mapped[Optional[Integer]] = mapped_column(Integer)
    uretim_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    recete_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    udi_human: Mapped[Optional[String]] = mapped_column(String)
    udi_barcode: Mapped[Optional[String]] = mapped_column(String)
    depo: Mapped[Optional['Depo']] = relationship(back_populates='is_emri')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='is_emri')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='is_emri')
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='is_emri')
    malzeme_recete: Mapped[Optional['MalzemeRecete']] = relationship(back_populates='is_emri')
    uretim_talep_detay: Mapped[Optional['UretimTalepDetay']] = relationship(back_populates='is_emri')
    hareket_sebebi: Mapped[Optional['HareketSebebi']] = relationship(back_populates='is_emri')
    kisi_1_2: Mapped[Optional['Kisi']] = relationship(back_populates='is_emri')
    recete_operasyonu: Mapped[Optional['ReceteOperasyonu']] = relationship(back_populates='is_emri')
    uygunsuzluk: Mapped[Optional['Uygunsuzluk']] = relationship(back_populates='is_emri')
    alinan_iade: Mapped[Optional['AlinanIade']] = relationship(back_populates='is_emri')
    islem_merkezi: Mapped[Optional['IslemMerkezi']] = relationship(back_populates='is_emri')