from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class IsEmriOperasyonu(Base):
    __tablename__ = 'is_emri_operasyonu'

    islem_sirasi: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    operasyon_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    durus_detay_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    durumu: Mapped[Optional[String]] = mapped_column(String)
    durus_baslangic: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    durus_bitis: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    islem_baslangic: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    islem_bitis: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    islem_suresi: Mapped[Optional[Float]] = mapped_column(Float)
    isemri_no: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    miktar_giren: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_kabul: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_red: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_sartli_kabul: Mapped[Optional[Float]] = mapped_column(Float)
    kimlik_no: Mapped[Optional[Float]] = mapped_column(Float)
    tezgah_no: Mapped[Optional[String]] = mapped_column(String)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    proses_rapor_no: Mapped[Optional[String]] = mapped_column(String)
    miktar_kontrol: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_kayit: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_cikan: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_parca_red: Mapped[Optional[Float]] = mapped_column(Float)
    recete_no: Mapped[Optional[Float]] = mapped_column(Float)
    kayit_no: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_yil: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_ay: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    sk_plan_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    vakum_degeri: Mapped[Optional[Integer]] = mapped_column(Integer)
    yapistirma_suresi: Mapped[Optional[Integer]] = mapped_column(Integer)
    bekleme_suresi: Mapped[Optional[Integer]] = mapped_column(Integer)
    recete_detay_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    vakum_suresi: Mapped[Optional[Integer]] = mapped_column(Integer)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    is_emri: Mapped[Optional['IsEmri']] = relationship(back_populates='is_emri_operasyonu')
    operasyon: Mapped[Optional['Operasyon']] = relationship(back_populates='is_emri_operasyonu')
    durus_tipi: Mapped[Optional['DurusTipi']] = relationship(back_populates='is_emri_operasyonu')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='is_emri_operasyonu')
    tezgah: Mapped[Optional['Tezgah']] = relationship(back_populates='is_emri_operasyonu')
    recete_operasyonu: Mapped[Optional['ReceteOperasyonu']] = relationship(back_populates='is_emri_operasyonu')
    uygunsuzluk: Mapped[Optional['Uygunsuzluk']] = relationship(back_populates='is_emri_operasyonu')
    firma: Mapped[Optional['Firma']] = relationship(back_populates='is_emri_operasyonu')