from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Kisi(Base):
    __tablename__ = 'kisi'

    kimlik_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    adi: Mapped[Optional[String]] = mapped_column(String)
    soyadi: Mapped[Optional[String]] = mapped_column(String)
    baba_adi: Mapped[Optional[String]] = mapped_column(String)
    ana_adi: Mapped[Optional[String]] = mapped_column(String)
    meslegi: Mapped[Optional[String]] = mapped_column(String)
    dogum_yeri: Mapped[Optional[String]] = mapped_column(String)
    dogum_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kan_grubu: Mapped[Optional[String]] = mapped_column(String)
    cinsiyeti: Mapped[Optional[String]] = mapped_column(String)
    medeni_hali: Mapped[Optional[String]] = mapped_column(String)
    ev_tel: Mapped[Optional[String]] = mapped_column(String)
    cep_tel: Mapped[Optional[String]] = mapped_column(String)
    is_tel: Mapped[Optional[String]] = mapped_column(String)
    adres: Mapped[Optional[String]] = mapped_column(String)
    ssk_no: Mapped[Optional[String]] = mapped_column(String)
    ilgili_sirket: Mapped[Optional[String]] = mapped_column(String)
    ise_giris_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    isten_cikis_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    vergi_dairesi: Mapped[Optional[String]] = mapped_column(String)
    vergi_no: Mapped[Optional[String]] = mapped_column(String)
    birim_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    gorevi: Mapped[Optional[String]] = mapped_column(String)
    mesai_fl: Mapped[Optional[String]] = mapped_column(String)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    gorev_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    egitim_durumu: Mapped[Optional[String]] = mapped_column(String)
    takma_ad: Mapped[Optional[String]] = mapped_column(String)
    sifre: Mapped[Optional[String]] = mapped_column(String)
    ayakkabi_no: Mapped[Optional[String]] = mapped_column(String)
    ust_beden: Mapped[Optional[String]] = mapped_column(String)
    alt_beden: Mapped[Optional[String]] = mapped_column(String)
    sifresi: Mapped[Optional[String]] = mapped_column(String)
    kilit: Mapped[Optional[Float]] = mapped_column(Float)
    id: Mapped[Optional[Integer]] = mapped_column(Integer)
    password: Mapped[Optional[String]] = mapped_column(String)
    last_login: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    is_superuser: Mapped[Optional[Float]] = mapped_column(Float)
    username: Mapped[Optional[String]] = mapped_column(String)
    first_name: Mapped[Optional[String]] = mapped_column(String)
    email: Mapped[Optional[String]] = mapped_column(String)
    is_staff: Mapped[Optional[Float]] = mapped_column(Float)
    is_active: Mapped[Optional[Float]] = mapped_column(Float)
    date_joined: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    aktif: Mapped[Optional[Float]] = mapped_column(Float)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    organizasyon_birimi: Mapped[Optional['OrganizasyonBirimi']] = relationship(back_populates='kisi')
    organizasyon_birimi_1: Mapped[Optional['OrganizasyonBirimi']] = relationship(back_populates='kisi')