from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class MalzemeHareketi(Base):
    __tablename__ = 'malzeme_hareketi'

    depo_kodu: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    hareket_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    raf_omru: Mapped[Optional[Float]] = mapped_column(Float)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    lot_no: Mapped[Optional[String]] = mapped_column(String)
    giris_cikis_fl: Mapped[Optional[String]] = mapped_column(String)
    miktar: Mapped[Optional[Float]] = mapped_column(Float)
    birim: Mapped[Optional[String]] = mapped_column(String)
    gel_isemri_no: Mapped[Optional[String]] = mapped_column(String)
    geldigi_isemri: Mapped[Optional[String]] = mapped_column(String)
    git_isemri_no: Mapped[Optional[String]] = mapped_column(String)
    gittigi_isemri: Mapped[Optional[String]] = mapped_column(String)
    hareket_kodu: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    yil: Mapped[Optional[Float]] = mapped_column(Float)
    giris_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    belge_tipi: Mapped[Optional[String]] = mapped_column(String)
    belge_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    belge_no: Mapped[Optional[String]] = mapped_column(String)
    tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    son_kullanma_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    fas_yil: Mapped[Optional[Float]] = mapped_column(Float)
    fas_no: Mapped[Optional[Float]] = mapped_column(Float)
    isemri_no: Mapped[Optional[String]] = mapped_column(String)
    teslim_eden: Mapped[Optional[Float]] = mapped_column(Float)
    teslim_alan: Mapped[Optional[Float]] = mapped_column(Float)
    fas_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    fas_ay: Mapped[Optional[Float]] = mapped_column(Float)
    durumu: Mapped[Optional[String]] = mapped_column(String)
    kk_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    kk_yil: Mapped[Optional[Float]] = mapped_column(Float)
    kk_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    kk_sonucu: Mapped[Optional[String]] = mapped_column(String)
    ref_depo_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    ref_hareket_no: Mapped[Optional[Float]] = mapped_column(Float)
    krslm_malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    siparis_yil: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_ay: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_no: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    uyg_yil: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_ay: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    bekleten: Mapped[Optional[Float]] = mapped_column(Float)
    bekleme_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    bekleme_sebebi: Mapped[Optional[String]] = mapped_column(String)
    arsiv_lot_no: Mapped[Optional[String]] = mapped_column(String)
    iade_yil: Mapped[Optional[Float]] = mapped_column(Float)
    iade_ay: Mapped[Optional[Float]] = mapped_column(Float)
    iade_fis_no: Mapped[Optional[Float]] = mapped_column(Float)
    ce_bilgisi: Mapped[Optional[String]] = mapped_column(String)
    kayit_yili: Mapped[Optional[Float]] = mapped_column(Float)
    kayit_no: Mapped[Optional[Float]] = mapped_column(Float)
    kisa_kodu: Mapped[Optional[String]] = mapped_column(String)
    birim_fiyati: Mapped[Optional[Float]] = mapped_column(Float)
    sevk_yil: Mapped[Optional[Float]] = mapped_column(Float)
    sevk_ay: Mapped[Optional[Float]] = mapped_column(Float)
    sevk_no: Mapped[Optional[Float]] = mapped_column(Float)
    koli_no: Mapped[Optional[Float]] = mapped_column(Float)
    set_malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    set_lot_no: Mapped[Optional[String]] = mapped_column(String)
    bim_aciklama: Mapped[Optional[String]] = mapped_column(String)
    yeni_program: Mapped[Optional[Integer]] = mapped_column(Integer)
    satis_onayi: Mapped[Optional[Float]] = mapped_column(Float)
    iade_siparis_sira_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    uts_lot_no: Mapped[Optional[String]] = mapped_column(String)
    uts_uretim_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    uts_miktar: Mapped[Optional[Integer]] = mapped_column(Integer)
    uts_bildirim_durumu: Mapped[Optional[Float]] = mapped_column(Float)
    bt_aciklama: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    udi_barcode: Mapped[Optional[String]] = mapped_column(String)
    mh_yil: Mapped[Optional[Float]] = mapped_column(Float)
    udi_humancode: Mapped[Optional[String]] = mapped_column(String)
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='malzeme_hareketi')
    depo: Mapped[Optional['Depo']] = relationship(back_populates='malzeme_hareketi')
    siparis_sevk_kolisi: Mapped[Optional['SiparisSevkKolisi']] = relationship(back_populates='malzeme_hareketi')
    hareket_sebebi: Mapped[Optional['HareketSebebi']] = relationship(back_populates='malzeme_hareketi')
    kontrollu_kayit: Mapped[Optional['KontrolluKayit']] = relationship(back_populates='malzeme_hareketi')
    is_emri: Mapped[Optional['IsEmri']] = relationship(back_populates='malzeme_hareketi')
    malzeme_1: Mapped[Optional['Malzeme']] = relationship(back_populates='malzeme_hareketi')
    firma: Mapped[Optional['Firma']] = relationship(back_populates='malzeme_hareketi')
    is_emri_1: Mapped[Optional['IsEmri']] = relationship(back_populates='malzeme_hareketi')
    tedarikci_emri: Mapped[Optional['TedarikciEmri']] = relationship(back_populates='malzeme_hareketi')
    is_emri_1_2: Mapped[Optional['IsEmri']] = relationship(back_populates='malzeme_hareketi')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='malzeme_hareketi')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='malzeme_hareketi')
    gecici_stok: Mapped[Optional['GeciciStok']] = relationship(back_populates='malzeme_hareketi')
    malzeme_hareketi: Mapped[Optional['MalzemeHareketi']] = relationship(back_populates='malzeme_hareketi')
    malzeme_1_2: Mapped[Optional['Malzeme']] = relationship(back_populates='malzeme_hareketi')
    uygunsuzluk: Mapped[Optional['Uygunsuzluk']] = relationship(back_populates='malzeme_hareketi')
    para_birimi: Mapped[Optional['ParaBirimi']] = relationship(back_populates='malzeme_hareketi')
    kisi_1_2: Mapped[Optional['Kisi']] = relationship(back_populates='malzeme_hareketi')
    alinan_iade: Mapped[Optional['AlinanIade']] = relationship(back_populates='malzeme_hareketi')