from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Malzeme(Base):
    __tablename__ = 'malzeme'

    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    grup_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    malzeme_adi: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    birimi: Mapped[Optional[String]] = mapped_column(String)
    birim_agirligi: Mapped[Optional[Float]] = mapped_column(Float)
    tanim_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    etiket_cinsi: Mapped[Optional[Integer]] = mapped_column(Integer)
    opsn: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    set_fl: Mapped[Optional[Float]] = mapped_column(Float)
    tanimi: Mapped[Optional[String]] = mapped_column(String)
    miktar_emniyet_1: Mapped[Optional[Float]] = mapped_column(Float)
    temin_suresi: Mapped[Optional[Integer]] = mapped_column(Integer)
    sure_kodu: Mapped[Optional[String]] = mapped_column(String)
    miktar_emniyet_2: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_urun_agac: Mapped[Optional[Float]] = mapped_column(Float)
    opsiyon_adi: Mapped[Optional[String]] = mapped_column(String)
    plan_fl: Mapped[Optional[String]] = mapped_column(String)
    resim_no: Mapped[Optional[String]] = mapped_column(String)
    recete_no: Mapped[Optional[Float]] = mapped_column(Float)
    siralama: Mapped[Optional[Float]] = mapped_column(Float)
    sk_plan_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    uretim_alarmi: Mapped[Optional[Float]] = mapped_column(Float)
    iptal_nedeni: Mapped[Optional[String]] = mapped_column(String)
    miktar_eldeki: Mapped[Optional[Float]] = mapped_column(Float)
    tarih_eldeki: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    miktar_bloke: Mapped[Optional[Float]] = mapped_column(Float)
    tarih_uretim: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    miktar_hesap: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_hedef: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_oncelikli_hedef: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_fasonda: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_fasona: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_satinalma: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_satinalinacak: Mapped[Optional[Float]] = mapped_column(Float)
    oncelik: Mapped[Optional[String]] = mapped_column(String)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    bitis_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    miktar_is_emri: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_acilmamis_ie: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_mp_uretim: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_bekleme_bolgesi: Mapped[Optional[Float]] = mapped_column(Float)
    miktar_bek_bol_cikilan: Mapped[Optional[Float]] = mapped_column(Float)
    urun_grup_no: Mapped[Optional[Float]] = mapped_column(Float)
    birimi_2: Mapped[Optional[String]] = mapped_column(String)
    donusum_katsayisi: Mapped[Optional[Float]] = mapped_column(Float)
    kisa_kodu: Mapped[Optional[String]] = mapped_column(String)
    edinme_maliyeti: Mapped[Optional[Float]] = mapped_column(Float)
    bagimli_malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    teknik_ozellik: Mapped[Optional[String]] = mapped_column(String)
    ubb_fl: Mapped[Optional[String]] = mapped_column(String)
    tpsn_malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    log_record_id: Mapped[Optional[String]] = mapped_column(String)
    skt_fl: Mapped[Optional[Integer]] = mapped_column(Integer)
    resim_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    gercek_resim_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    ce_fl: Mapped[Optional[Integer]] = mapped_column(Integer)
    stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    stok_konsinye: Mapped[Optional[String]] = mapped_column(String)
    gecici_stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    kisa_adi: Mapped[Optional[String]] = mapped_column(String)
    recete_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    malzeme_relation_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    kutu_id: Mapped[Optional[Integer]] = mapped_column(Integer)
    euromed_stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    miktar_konsinye: Mapped[Optional[Float]] = mapped_column(Float)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    malzeme_grubu: Mapped[Optional['MalzemeGrubu']] = relationship(back_populates='malzeme')
    para_birimi: Mapped[Optional['ParaBirimi']] = relationship(back_populates='malzeme')
    malzeme_recete: Mapped[Optional['MalzemeRecete']] = relationship(back_populates='malzeme')
    sk_plani: Mapped[Optional['SkPlani']] = relationship(back_populates='malzeme')
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='malzeme')
    malzeme_birimi: Mapped[Optional['MalzemeBirimi']] = relationship(back_populates='malzeme')
    urun_grubu: Mapped[Optional['UrunGrubu']] = relationship(back_populates='malzeme')
    malzeme_birimi_1: Mapped[Optional['MalzemeBirimi']] = relationship(back_populates='malzeme')
    malzeme_kutu: Mapped[Optional['MalzemeKutu']] = relationship(back_populates='malzeme')