from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class MalzemeUbbEk(Base):
    __tablename__ = 'malzeme_ubb_ek'

    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    ubb_no_tipi: Mapped[Optional[String]] = mapped_column(String)
    ubb_no: Mapped[Optional[String]] = mapped_column(String)
    marka: Mapped[Optional[String]] = mapped_column(String)
    katalog_no: Mapped[Optional[String]] = mapped_column(String)
    unspsc_kodu: Mapped[Optional[String]] = mapped_column(String)
    unspsc_sinif_adi: Mapped[Optional[String]] = mapped_column(String)
    ithal_imal_fl: Mapped[Optional[String]] = mapped_column(String)
    ambalaj_turu: Mapped[Optional[String]] = mapped_column(String)
    ambalaj_ici_miktar: Mapped[Optional[Float]] = mapped_column(Float)
    ambalaj_birimi: Mapped[Optional[String]] = mapped_column(String)
    genislik: Mapped[Optional[Float]] = mapped_column(Float)
    yukseklik: Mapped[Optional[Float]] = mapped_column(Float)
    derinlik: Mapped[Optional[Float]] = mapped_column(Float)
    gmdn_kodu: Mapped[Optional[String]] = mapped_column(String)
    gmdn_adi: Mapped[Optional[String]] = mapped_column(String)
    yonetmelik: Mapped[Optional[String]] = mapped_column(String)
    ubb_brans_kodu: Mapped[Optional[String]] = mapped_column(String)
    ubb_brans_adi: Mapped[Optional[String]] = mapped_column(String)
    durumu: Mapped[Optional[String]] = mapped_column(String)
    mevzuat_kaydi_fl: Mapped[Optional[String]] = mapped_column(String)
    etiket_adi: Mapped[Optional[String]] = mapped_column(String)
    fiyat: Mapped[Optional[Float]] = mapped_column(Float)
    fiyat_sonlanma_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    sertifika_adi: Mapped[Optional[String]] = mapped_column(String)
    sertifika_bitis_t: Mapped[Optional[String]] = mapped_column(String)
    kisa_kodu: Mapped[Optional[String]] = mapped_column(String)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    ubb_kayit_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    belgelendirme_kurulusu: Mapped[Optional[String]] = mapped_column(String)
    uygunluk_beyani: Mapped[Optional[String]] = mapped_column(String)
    ce_sinifi: Mapped[Optional[String]] = mapped_column(String)
    sut_kodu: Mapped[Optional[String]] = mapped_column(String)
    sut_adi: Mapped[Optional[String]] = mapped_column(String)
    raf_omru: Mapped[Optional[String]] = mapped_column(String)
    son_onay_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    opsn: Mapped[Optional[String]] = mapped_column(String)
    ubb_yedek: Mapped[Optional[String]] = mapped_column(String)
    gecici_ean: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='malzeme_ubb_ek')
    para_birimi: Mapped[Optional['ParaBirimi']] = relationship(back_populates='malzeme_ubb_ek')