from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class TbResimTbl(Base):
    __tablename__ = 'tb_resim_tbl'

    resim_grubu: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    sira_no: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    asama_adi: Mapped[Optional[String]] = mapped_column(String)
    kod: Mapped[Optional[String]] = mapped_column(String)
    tanim: Mapped[Optional[String]] = mapped_column(String)
    uretim: Mapped[Optional[String]] = mapped_column(String)
    proses: Mapped[Optional[String]] = mapped_column(String)
    son_kk: Mapped[Optional[String]] = mapped_column(String)
    giris_kk: Mapped[Optional[String]] = mapped_column(String)
    teknik_dosya: Mapped[Optional[String]] = mapped_column(String)
    cnc: Mapped[Optional[String]] = mapped_column(String)
    diger: Mapped[Optional[String]] = mapped_column(String)
    markalama: Mapped[Optional[String]] = mapped_column(String)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    goruntu_no: Mapped[Optional[Float]] = mapped_column(Float)
    yk_resim: Mapped[Optional[String]] = mapped_column(String)
    dagitim_1: Mapped[Optional[String]] = mapped_column(String)
    dagitim_2: Mapped[Optional[String]] = mapped_column(String)
    dagitim_3: Mapped[Optional[String]] = mapped_column(String)
    dagitim_4: Mapped[Optional[String]] = mapped_column(String)
    dagitim_5: Mapped[Optional[String]] = mapped_column(String)
    dagitim_6: Mapped[Optional[String]] = mapped_column(String)
    dagitim_7: Mapped[Optional[String]] = mapped_column(String)
    revizyon_1: Mapped[Optional[String]] = mapped_column(String)
    revizyon_2: Mapped[Optional[String]] = mapped_column(String)
    revizyon_3: Mapped[Optional[String]] = mapped_column(String)
    revizyon_4: Mapped[Optional[String]] = mapped_column(String)
    revizyon_5: Mapped[Optional[String]] = mapped_column(String)
    revizyon_6: Mapped[Optional[String]] = mapped_column(String)
    revizyon_7: Mapped[Optional[String]] = mapped_column(String)
    tedarikci1: Mapped[Optional[String]] = mapped_column(String)
    tedarikci2: Mapped[Optional[String]] = mapped_column(String)
    tedarikci3: Mapped[Optional[String]] = mapped_column(String)
    tedarikci4: Mapped[Optional[String]] = mapped_column(String)
    tedarikci5: Mapped[Optional[String]] = mapped_column(String)
    kritik_olcu: Mapped[Optional[String]] = mapped_column(String)
    tb__sira_no: Mapped[Optional[String]] = mapped_column(String)
    tb__resim_grubu: Mapped[Optional[String]] = mapped_column(String)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    bilgiler_tam: Mapped[Optional[String]] = mapped_column(String)
    dis_tic: Mapped[Optional[String]] = mapped_column(String)
    elektronik: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    tb_resim_tbl: Mapped[Optional['TbResimTbl']] = relationship(back_populates='tb_resim_tbl')
    firma: Mapped[Optional['Firma']] = relationship(back_populates='tb_resim_tbl')
    resim_grubu: Mapped[Optional['ResimGrubu']] = relationship(back_populates='tb_resim_tbl')
    goruntu: Mapped[Optional['Goruntu']] = relationship(back_populates='tb_resim_tbl')