from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class TedarikciEmriDetay(Base):
    __tablename__ = 'tedarikci_emri_detay'

    fason_yil: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    fason_ay: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    fason_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    sira_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    malzeme_no: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    miktar: Mapped[Optional[Float]] = mapped_column(Float)
    oncelik: Mapped[Optional[String]] = mapped_column(String)
    kayit_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    giris_cikis_fl: Mapped[Optional[String]] = mapped_column(String)
    talep_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    gerekce: Mapped[Optional[Float]] = mapped_column(Float)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    iptal_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kimlik_no: Mapped[Optional[Float]] = mapped_column(Float)
    onerilen_tarih: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kesinlesen_tarih: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iptal_nedeni: Mapped[Optional[String]] = mapped_column(String)
    iptal_eden: Mapped[Optional[Float]] = mapped_column(Float)
    kapandi_fl: Mapped[Optional[String]] = mapped_column(String)
    kapanma_nedeni: Mapped[Optional[String]] = mapped_column(String)
    siparis_sevk_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    sevk_miktari: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_edilen_miktar: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_teslim_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    stok_kodu: Mapped[Optional[String]] = mapped_column(String)
    opsn: Mapped[Optional[String]] = mapped_column(String)
    malzeme_adi: Mapped[Optional[String]] = mapped_column(String)
    lot_no: Mapped[Optional[String]] = mapped_column(String)
    materyal: Mapped[Optional[String]] = mapped_column(String)
    ce_bilgisi: Mapped[Optional[String]] = mapped_column(String)
    ambalaj: Mapped[Optional[String]] = mapped_column(String)
    etiket: Mapped[Optional[String]] = mapped_column(String)
    markalama: Mapped[Optional[String]] = mapped_column(String)
    kontrol_lot_no: Mapped[Optional[String]] = mapped_column(String)
    birim_fiyati: Mapped[Optional[Integer]] = mapped_column(Integer)
    para_birimi: Mapped[Optional[String]] = mapped_column(String)
    isemri_no: Mapped[Optional[Float]] = mapped_column(Float)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    tedarikci_emri: Mapped[Optional['TedarikciEmri']] = relationship(back_populates='tedarikci_emri_detay')
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='tedarikci_emri_detay')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri_detay')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri_detay')