from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class TedarikciEmri(Base):
    __tablename__ = 'tedarikci_emri'

    fason_yil: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    fason_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer, nullable=False)
    duzenleyen_kimlik: Mapped[Optional[Float]] = mapped_column(Float)
    onaylayan_kimlik: Mapped[Optional[Float]] = mapped_column(Float)
    ilgili_kisi: Mapped[Optional[String]] = mapped_column(String)
    duzenleme_z: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    istenen_termin: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    termin_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    yollama_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    donus_t: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    iptal_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    onerilen_termin: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    fason_ay: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    emir_tipi: Mapped[Optional[String]] = mapped_column(String)
    siparis_ref_no: Mapped[Optional[String]] = mapped_column(String)
    kapandi_fl: Mapped[Optional[String]] = mapped_column(String)
    lot_fl: Mapped[Optional[String]] = mapped_column(String)
    iptal_eden: Mapped[Optional[Float]] = mapped_column(Float)
    iptal_nedeni: Mapped[Optional[String]] = mapped_column(String)
    kontrol_eden: Mapped[Optional[Float]] = mapped_column(Float)
    onay_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    kontrol_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    siparis_ay: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_yil: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_no: Mapped[Optional[Float]] = mapped_column(Float)
    irsaliye_no: Mapped[Optional[String]] = mapped_column(String)
    sertifia_no: Mapped[Optional[String]] = mapped_column(String)
    durumu: Mapped[Optional[String]] = mapped_column(String)
    satinalma_birimi: Mapped[Optional[String]] = mapped_column(String)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    firma: Mapped[Optional['Firma']] = relationship(back_populates='tedarikci_emri')
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri')
    kisi_1_2: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri')
    kisi_1_2_3: Mapped[Optional['Kisi']] = relationship(back_populates='tedarikci_emri')