from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class UretimTalebi(Base):
    __tablename__ = 'uretim_talebi'

    yil: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    fis_no: Mapped[Optional[Float]] = mapped_column(Float, nullable=False)
    teslim_eden: Mapped[Optional[Float]] = mapped_column(Float)
    teslim_alan: Mapped[Optional[Float]] = mapped_column(Float)
    duzenleme_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    tamir_nedeni: Mapped[Optional[String]] = mapped_column(String)
    siparis_no: Mapped[Optional[String]] = mapped_column(String)
    iade_fis_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    iade_fis_no: Mapped[Optional[String]] = mapped_column(String)
    set_adi: Mapped[Optional[String]] = mapped_column(String)
    set_no: Mapped[Optional[Float]] = mapped_column(Float)
    uretim_emri_tip_kodu: Mapped[Optional[Float]] = mapped_column(Float)
    aciklama: Mapped[Optional[String]] = mapped_column(String)
    durum_fl: Mapped[Optional[String]] = mapped_column(String, nullable=False)
    kapanis_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    onaylayan: Mapped[Optional[Float]] = mapped_column(Float)
    onay_tarihi: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    malzeme_set_no: Mapped[Optional[Integer]] = mapped_column(Integer)
    firma_kodu: Mapped[Optional[Integer]] = mapped_column(Integer)
    ref_belge: Mapped[Optional[String]] = mapped_column(String)
    sevk_sekli: Mapped[Optional[String]] = mapped_column(String)
    stok_amacli_fl: Mapped[Optional[String]] = mapped_column(String)
    uubf_no: Mapped[Optional[String]] = mapped_column(String)
    siparis_yil: Mapped[Optional[Float]] = mapped_column(Float)
    siparis_ay: Mapped[Optional[Float]] = mapped_column(Float)
    siparisno: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_yil: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_ay: Mapped[Optional[Float]] = mapped_column(Float)
    uyg_rapor_no: Mapped[Optional[Float]] = mapped_column(Float)
    iade_yil: Mapped[Optional[Float]] = mapped_column(Float)
    iade_ay: Mapped[Optional[Float]] = mapped_column(Float)
    iade_fisno: Mapped[Optional[Float]] = mapped_column(Float)
    ekleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    ensonguncelleyen_kullanici_kimlik_no: Mapped[Optional[String]] = mapped_column(String)
    eklenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    enson_guncellenme_zamani: Mapped[Optional[DateTime]] = mapped_column(DateTime)
    mac_address: Mapped[Optional[String]] = mapped_column(String)
    guncelleyen_mac_address: Mapped[Optional[String]] = mapped_column(String)
    kisi: Mapped[Optional['Kisi']] = relationship(back_populates='uretim_talebi')
    kisi_1: Mapped[Optional['Kisi']] = relationship(back_populates='uretim_talebi')
    uretim_emri_tipi: Mapped[Optional['UretimEmriTipi']] = relationship(back_populates='uretim_talebi')
    kisi_1_2: Mapped[Optional['Kisi']] = relationship(back_populates='uretim_talebi')
    malzeme: Mapped[Optional['Malzeme']] = relationship(back_populates='uretim_talebi')
    firma: Mapped[Optional['Firma']] = relationship(back_populates='uretim_talebi')
    alinan_siparis: Mapped[Optional['AlinanSiparis']] = relationship(back_populates='uretim_talebi')
    uygunsuzluk: Mapped[Optional['Uygunsuzluk']] = relationship(back_populates='uretim_talebi')
    alinan_iade: Mapped[Optional['AlinanIade']] = relationship(back_populates='uretim_talebi')